name: Hangman
on: [push, pull_request]

jobs:

  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: axel-op/dart-package-analyzer/with-full-sdk@stable
      - uses: axel-op/dart-package-analyzer@stable
        with:
          # Required:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional:
          relativePath: packages/mypackage/
          minAnnotationLevel: info
