name: Flutter-Apps

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: axel-op/dart-package-analyzer@v2.0.0
    - name: Dart/Flutter Package Analyzer
      run: pub get
    - name: Run tests
      run: pub run test
